### ISSUE TITLE
Cannot read properties of undefined (reading 'date')

### ISSUE THREAD

**Issue by n3rd3x3** [railwayapp/blog#13]
After following all of the steps in the tutorial, I'm getting this error:
```
> Build error occurred
 
TypeError: Cannot read properties of undefined (reading 'date')
at /workspace/.next/server/chunks/490.js:32:50
at Array.filter (<anonymous>)
at getDatabase (/workspace/.next/server/chunks/490.js:32:20)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async getStaticPaths (/workspace/.next/server/pages/p/[slug].js:515:19)
at async buildStaticPaths (/workspace/node_modules/next/dist/build/utils.js:497:31)
at async /workspace/node_modules/next/dist/build/utils.js:640:119
at async Span.traceAsyncFn (/workspace/node_modules/next/dist/trace/trace.js:75:20) {
type: 'TypeError'
}
 
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 
error Command failed with exit code 1.
 
ERROR: failed to build: exit status 1
 
ERROR: failed to build: executing lifecycle: failed with status code: 51
 ```
 If for whatever reason my table has any errors, feel free to check it out here: https://n3rd3x3.notion.site/f1faacfd89bd45ce888b5e335245a176?v=7062f5b173344f50bda90c1dda1ba70c

**Comment by n3rd3x3** [comment]
due to this repo being seemingly dead, i am closing this
feel free to comment in the case that this is ever seen
